name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: |
            docker-layer-caching-${{ github.workflow }}-${{ matrix.restyler }}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-${{ matrix.restyler }}-
      - name: Build
        run: |
          docker build --tag restyled/sdk .

  push:
    if: github.ref == "refs/heads/main"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.dockerhub_username }}
          DOCKERHUB_PASSWORD: ${{ secrets.dockerhub_password }}
        run: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

      - name: Tag & Push
        run: |
          docker tag restyled/sdk restyled/sdk:main
          docker push restyled/sdk:main
